version: 0.0
os: linux
files:
  - source: /
    destination: /home/workdir/scripts/php-scripts/exehda
    owner: root
    group: root
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
    mode: 764
    type:
      - file    
  - object: /
    owner: root
    group: root
    mode: 764
    type:
      - directory      
hooks:
  AfterInstall:
    - location: /aws_scripts/after_install.sh          
    